### ISSUE TITLE
Slipping random number in, when calling an input from website (Custom Commands)

### ISSUE THREAD

**Issue by adhiariawan** [Arraying/Arraybot#4]
There's a command I've been working on which I have trouble getting it to work:

`//commands create sig`
`//commands setsyntax sig startswith`
`//commands setvalue sig http://www.novaragnarok.com/ROChargenPHP/newsig/{input}/{1;2;3;4;5;6;7;8;9}/{1;2;3;4;5;6;7;8;9}`

What I had expected :

> http://www.novaragnarok.com/ROChargenPHP/newsig/(input)/(random number from 1 to 9)/(random number from 1 to 9)`

But it returns the output wrong..
Is there a way to achieve this at the moment?
Thanks.

**Comment by Arraying** [comment]
Hey! This may sound terrible but there is currently a solution to this. Simply set the value to something like this:

 `http://www.novaragnarok.com/ROChargenPHP/newsig/{input}/1/1;http://www.novaragnarok.com/ROChargenPHP/newsig/{input}/1/2;http://www.novaragnarok.com/ROChargenPHP/newsig/{input}/1/3`

Now this solution is actually quite disgusting due to a few different reasons:
1) There is a maximum custom command value (thanks Discord for a character limit)
2) It's impossible/painful to have a huge range of numbers

I quite like the way you used braces for the random thing, so that may be something I'll implement next version. I've actually got a placeholder for a random number though. Using `{random}` will replace it with a number between 0 or 1 (can't remember, been a while) and Java's maximum short value (32,767).

**Comment by xJade00** [comment]
This will be fixed in v5 with scripting.
